version: '1'

services:
  # Service Node.js
  nodeapp:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - sonar-network

  # Service SonarQube
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonar-network
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

networks:
  sonar-network:
    external: true